/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ithembaroh;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sfiso
 */
public class frmEdit extends javax.swing.JFrame {

    /**
     * Creates new form frmEdit
     */
    public frmEdit() {
        initComponents();  
    }

    public String strOldID;
    
    private void mUpdateClientDetails() // updates the data in the databse
    {
        //Connection conMySQLConnectionString = null;
        String URL = "jdbc:mysql://localhost:3306/burial_society_db";
        String User = "root";
        String Password = "WeWillMakeIt@Life";
          
        String strPmLName = null;
        String strPmFName = null;
        String strID = null;  
        String strPmDOB = null;
        String strPmAddress  = null;
        String strPmTel = null;
        String strPmEmail = null;   
        
        try
        {
            Connection conMySQLConnectionString = DriverManager.getConnection(URL, User, Password);
            conMySQLConnectionString.setAutoCommit(false);
            
            try(Statement myStatement = conMySQLConnectionString.createStatement())
            {
                for(int i = 0; i < tblEdit.getRowCount(); i++)
                {
                    for(int j = 0; j < tblEdit.getColumnCount(); j++)
                    {
                        strPmLName = tblEdit.getValueAt(i, 0).toString().toUpperCase();
                        strPmFName = tblEdit.getValueAt(i, 1).toString().toUpperCase();
                        strID = tblEdit.getValueAt(i, 2).toString().toUpperCase();
                        strPmDOB = tblEdit.getValueAt(i, 3).toString().toUpperCase();
                        strPmAddress = tblEdit.getValueAt(i, 4).toString().toUpperCase();
                        strPmTel = tblEdit.getValueAt(i, 5).toString().toUpperCase();
                        strPmEmail = tblEdit.getValueAt(i, 6).toString().toUpperCase();
                    }
                    String strQuery = "UPDATE principal_members "
                                    + "SET LName = " + "'" + strPmLName + "'" + ", FName = " + "'" + strPmFName + "'" + ", ID_Num = " + "'" + strID + "'" + ", DOB = " + "'" + strPmDOB + "'"
                                    + ", Address = " + "'" + strPmAddress + "'" + ", Tel = " + "'" + strPmTel + "'" + ", Email = " + "'" + strPmEmail + "'"
                                    + "WHERE ID_Num = " + "'" + strOldID + "'" ;
                    
                    myStatement.addBatch(strQuery);
                 
                    strQuery = "UPDATE beneficiaries "
                             + "SET PM_ID_Num = " + "'" + strID + "'" 
                             + "WHERE PM_ID_Num = " + "'" + strOldID + "'" ;
                    myStatement.addBatch(strQuery);
                }
                
                myStatement.executeBatch();
                conMySQLConnectionString.commit();
                conMySQLConnectionString.setSavepoint();
                conMySQLConnectionString.rollback();
                myStatement.close();
                
                JOptionPane.showMessageDialog(rootPane, "Data has been successfully updated.");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e);
            }    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the conString structor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEdit = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDIT");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        tblEdit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Surname", "First Names", "ID Number", "Date Of Birth", "Address", "Telephone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEdit.setRowHeight(21);
        tblEdit.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEdit);
        if (tblEdit.getColumnModel().getColumnCount() > 0) {
            tblEdit.getColumnModel().getColumn(0).setResizable(false);
            tblEdit.getColumnModel().getColumn(1).setResizable(false);
            tblEdit.getColumnModel().getColumn(2).setResizable(false);
            tblEdit.getColumnModel().getColumn(3).setResizable(false);
            tblEdit.getColumnModel().getColumn(4).setResizable(false);
            tblEdit.getColumnModel().getColumn(5).setResizable(false);
            tblEdit.getColumnModel().getColumn(6).setResizable(false);
        }

        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 51, 51));
        btnBack.setText("Cancel");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 51, 255));
        btnRefresh.setText("Save");
        btnRefresh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
 mUpdateClientDetails();
 this.dispose();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblEdit;
    // End of variables declaration//GEN-END:variables
}
